name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Out Directory
        run: mkdir gh_out

      - name: Build (macOS/amd64)
        run: |
          cargo build --target x86_64-apple-darwin --release --verbose
          cp target/x86_64-apple-darwin/release/aobscan-cli gh_out/aobscan-macos-amd64

      - name: Build (macOS/arm64)
        run: |
          cargo build --target aarch64-apple-darwin --release --verbose
          cp target/aarch64-apple-darwin/release/aobscan-cli gh_out/aobscan-macos-arm64

      - name: Build (Linux/amd64)
        run: |
          cargo build --target x86_64-unknown-linux-gnu --release --verbose
          cp target/x86_64-unknown-linux-gnu/release/aobscan-cli gh_out/aobscan-linux-amd64

      - name: Build (Linux/arm64)
        run: |
          cargo build --target aarch64-unknown-linux-gnu --release --verbose
          cp target/aarch64-unknown-linux-gnu/release/aobscan-cli gh_out/aobscan-linux-arm64

      - name: Build (Windows/amd64)
        run: |
          cargo build --target x86_64-pc-windows-msvc --release --verbose
          cp target/x86_64-pc-windows-msvc/release/aobscan-cli.exe gh_out/aobscan-windows-amd64.exe

      - name: Build (Windows/arm64)
        run: |
          cargo build --target aarch64-pc-windows-msvc --release --verbose
          cp target/aarch64-pc-windows-msvc/release/aobscan-cli.exe gh_out/aobscan-windows-arm64.exe

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: gh_out/*
