name: Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ ubuntu-latest, macos-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          #- os: ubuntu-latest
          #  target: aarch64-unknown-linux-gnu
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #- os: macos-latest
          #  target: aarch64-apple-darwin
          # - os: windows-latest
          #  target: x86_64-pc-windows-msvc
          #- os: windows-latest
          #  target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.os }}
    env:
      NAME: aobscan
      TARGET: ${{ matrix.target }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{matrix.TARGET}}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust Toolchain
        run: rustup target add $TARGET

      - name: Build
        run: cargo build --release --verbose --target $TARGET
